# Generated by Django 4.1.4 on 2022-12-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member_info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("台灣", "台灣"),
                            ("日本", "日本"),
                            ("香港", "香港"),
                            ("越南", "越南"),
                        ],
                        default="台灣",
                        max_length=4,
                    ),
                ),
                ("room", models.PositiveIntegerField()),
                ("bed", models.SlugField(max_length=10)),
                ("member_class", models.CharField(max_length=5)),
                ("student_ID", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=5)),
                ("ID_number", models.CharField(max_length=10)),
                ("birthday", models.DateField()),
                ("phone", models.CharField(max_length=10)),
                ("home_phone", models.CharField(max_length=10)),
                ("address", models.CharField(max_length=200)),
                ("emergency_contact", models.CharField(max_length=10)),
                ("emergency_contact_phone", models.CharField(max_length=10)),
            ],
        ),
    ]
